---
title: "project part 3"
author: "Owen Jennings"
date: "4/7/2022"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)

```

```{r}
taxis = read.csv("https://github.com/ebmorelli/479-nyc-transport/raw/main/taxis.csv")

```

```{r}

taxis <- taxis %>% 
  mutate(cost_per_mile = totalAmount/totalDistance) %>% 
  drop_na()

taxis = taxis[taxis$totalDistance != 0, ]
taxis <- subset(taxis, taxis$cost_per_mile >1 ) 

```

```{r}
taxis = sample_n(taxis, 2000)
```

```{r}
taxis$pickupTime <- format(as.POSIXct(taxis$pickupTime), format='%H:%M:%S')
```

```{r}
ggplot(data=taxis, aes(x=pickupTime, y=cost_per_mile)) + geom_point() 
```

```{r}
class(taxis$pickupTime)
```

#Take a look at this code, is this what you're trying to do?
#taxiHours = taxis %>% 
#  drop_na(passengerCount) %>%
#  mutate(starthour = hour(pickupTime)) %>%
#  group_by(starthour) %>%
#  summarize(amount = mean(totalAmount), apm = mean(totalAmount) / mean(totalDistance)) %>%
#  filter(apm < 1000000, apm > 0)

#ggplot(taxiHours) +
#  geom_bar(aes(x = starthour, y = apm),stat="identity")




